dataset: 'kittisf'
save_path: 'ckpt/flow/kittisf/kittisf_unsup/epoch=23.ckpt'

data:
#  root: '/home/ziyang/Desktop/Datasets/KITTI_SceneFlow'
  root: '/media/SSD/ziyang/Datasets/KITTI_SceneFlow'

flownet:
  npoint: 8192
  use_instance_norm: False
  loc_flow_nn: 16
  loc_flow_rad: 1.5
  k_decay_fact: 1.0