dataset: 'ogcdr'
save_path: 'ckpt/seg/ogcdr/ogcdr_sup'

data:
#  root: '/home/ziyang/Desktop/Datasets/OGC_DynamicRoom'
  root: '/media/SSD/ziyang/Datasets/OGC_DynamicRoom'
  aug_transform: False
  aug_transform_args: None
  decentralize: False

epochs: 40
batch_size: 32

lr: 1.0e-3
lr_decay: 1.0
lr_clip: 1.0e-5

bn_momentum: 0.9
bn_decay: 1.0
weight_decay: 0.0
decay_step: 200000

segnet:
  n_slot: 8
  n_point: 2048
  use_xyz: True
  n_transformer_layer: 2
  transformer_embed_dim: 128
  transformer_input_pos_enc: False

loss:
  use_focal: False
  focal_loss_params:
    alpha: 0.25
    gamma: 2
  weights: [2.0, 0]   # ['ce', 'dice']