{
    "02828884": {
        "id": "02828884",
        "name": "bench"
    },
    "02933112": {
        "id": "02933112",
        "name": "cabinet"
    },
    "03001627": {
        "id": "03001627",
        "name": "chair"
    },
    "03211117": {
        "id": "03211117",
        "name": "display,video display"
    },
    "03636649": {
        "id": "03636649",
        "name": "lamp"
    },
    "04256520": {
        "id": "04256520",
        "name": "sofa,couch,lounge"
    },
    "04379243": {
        "id": "04379243",
        "name": "table"
    }
}
