dataset: 'kittisf'
save_path: 'ckpt/seg/kittisf/kittisf_unsup'

data:
#  root: '/home/ziyang/Desktop/Datasets/KITTI_SceneFlow_downsampled'
  root: '/media/SSD/ziyang/Datasets/KITTI_SceneFlow_downsampled'
  train_mapping: 'data_prepare/kittisf/splits/train.txt'
  val_mapping: 'data_prepare/kittisf/splits/val.txt'
  aug_transform_args:
    scale_low: 0.95
    scale_high: 1.05
    degree_range: [0, 180, 0]
    shift_range: [1, 0.1, 1]
  decentralize: True
aug_transform_epoch: 0
predflow_path: flowstep3d
ignore_npoint_thresh: 50

epochs: 200
batch_size: 4

lr: 1.0e-3
lr_decay: 1.0
lr_clip: 1.0e-5

bn_momentum: 0.9
bn_decay: 1.0
weight_decay: 0.0
decay_step: 200000

segnet:
  n_slot: 10
  n_point: 8192
  use_xyz: True
  n_transformer_layer: 2
  transformer_embed_dim: 128
  transformer_input_pos_enc: False

loss:
  weights: [10.0, 0.1, 0.1]   # ['dynamic', 'smooth', 'invariance]
  start_steps: [0, 100, 1000]   # ['dynamic', 'smooth', 'invariance]
  dynamic_loss_params:
    loss_norm: 2
  smooth_loss_params:
    w_knn: 3.
    w_ball_q: 1.
    knn_loss_params:
      k: 32
      radius: 1.
      loss_norm: 1
    ball_q_loss_params:
      k: 64
      radius: 2.
      loss_norm: 1
  invariance_loss_params:
    loss_norm: 2