dataset: 'sapien'
save_path: 'ckpt/seg/sapien/sapien_sup'

data:
#  root: '/home/ziyang/Desktop/Datasets/MBS_SAPIEN'
  root: '/media/SSD/ziyang/Datasets/MBS_SAPIEN'
  aug_transform: True
  aug_transform_args:
    scale_low: 0.95
    scale_high: 1.05
    degree_range: [0, 180, 0]
    shift_range: [0, 0, 0]
  decentralize: False

epochs: 40
batch_size: 128

lr: 1.0e-3
lr_decay: 1.0
lr_clip: 1.0e-5

bn_momentum: 0.9
bn_decay: 1.0
weight_decay: 0.0
decay_step: 200000

segnet:
  n_slot: 8
  n_point: 512
  use_xyz: True
  n_transformer_layer: 2
  transformer_embed_dim: 128
  transformer_input_pos_enc: False

loss:
  use_focal: False
  focal_loss_params:
    alpha: 0.25
    gamma: 2
  weights: [2.0, 0]   # ['ce', 'dice']